# -*- coding: utf-8 -*-
"""wav2vec2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iUEdr0mg3X3gr7VTEA77mA01kRRO9iNi
"""



!unzip Dataset.zip

!pip install transformers evaluate librosa soundfile numpy torch jiwer

!python train-2.py \
--data_dir /content/Dataset \
--output_dir /content/output \
--wandb_proj my-asr-project \
--batch_size 8 \
--max_steps 1000 \
--save_steps 100 \
--eval_steps 100 \
--logging_steps 10 \
--learning_rate 1e-4